name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with GUI support
        run: |
            # Install Xvfb and dependencies
            sudo apt-get install -y xvfb libxrender1 libxtst6 libxi6
            
            # Run tests with virtual display
            Xvfb :99 -screen 0 1024x768x24 &
            export DISPLAY=:99
            
            # Run tests normally
            mvn test
            
            # Check results (optional - only if you want special handling)
            TEST_RESULT=$?
            if [ $TEST_RESULT -ne 0 ]; then
              echo "Tests failed - checking if due to GUI..."
              if grep -q "java.awt.HeadlessException" target/surefire-reports/*.txt; then
                echo "ERROR: GUI tests failed despite Xvfb - investigate!"
                exit 1
              else
                echo "Non-GUI test failures detected"
                exit 1
              fi
            fi