name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests (ignore errors with GUI but fail on failures)
        run: |
          # First run tests normally but capture exit code
          mvn test -Dmaven.test.failure.ignore=true
          TEST_RESULT=$?
          
          # Check surefire reports for test failures (not errors)
          if grep -q "Failures: [1-9]" target/surefire-reports/*.txt; then
            echo "Test failures detected (not just errors) - failing workflow"
            exit 1
          elif [ $TEST_RESULT -ne 0 ]; then
            echo "Build error detected - failing workflow"
            exit 1
          else
            echo "Only test errors (no failures) - allowing workflow to pass"
          fi
