name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Xvfb (for Swing GUI tests)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with full module access for Mockito
        run: |
          MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED \
                      --add-opens java.base/java.util=ALL-UNNAMED \
                      --add-opens java.base/java.io=ALL-UNNAMED \
                      --add-opens java.base/java.time=ALL-UNNAMED \
                      --add-opens java.base/java.nio=ALL-UNNAMED \
                      --add-opens java.base/java.lang.reflect=ALL-UNNAMED \
                      --add-opens java.desktop/javax.swing=ALL-UNNAMED \
                      --add-opens java.desktop/java.awt=ALL-UNNAMED \
                      --add-opens java.desktop/sun.awt=ALL-UNNAMED" \
          mvn test
